//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OsuPlayer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OsuPlayer.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Settings.
        /// </summary>
        public static string AudioSettingsTitle {
            get {
                return ResourceManager.GetString("AudioSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to customize.
        /// </summary>
        public static string CustomizeTitle {
            get {
                return ResourceManager.GetString("CustomizeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to donator stuff.
        /// </summary>
        public static string DonatorStuffTitle {
            get {
                return ResourceManager.GetString("DonatorStuffTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enter password to save.
        /// </summary>
        public static string EnterPasswordToSave {
            get {
                return ResourceManager.GetString("EnterPasswordToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enter playlistname.
        /// </summary>
        public static string EnterPlaylistNamePlaceholder {
            get {
                return ResourceManager.GetString("EnterPlaylistNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equalizer settings.
        /// </summary>
        public static string EqualizerSettingsText {
            get {
                return ResourceManager.GetString("EqualizerSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Settings.
        /// </summary>
        public static string GeneralSettingsTitle {
            get {
                return ResourceManager.GetString("GeneralSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import osu! collections.
        /// </summary>
        public static string ImportCollectionsTitle {
            get {
                return ResourceManager.GetString("ImportCollectionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to import osu! songs.
        /// </summary>
        public static string ImportSongsText {
            get {
                return ResourceManager.GetString("ImportSongsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to login to osu!player.
        /// </summary>
        public static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not logged in.
        /// </summary>
        public static string NotLoggedInText {
            get {
                return ResourceManager.GetString("NotLoggedInText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to open equalizer.
        /// </summary>
        public static string OpenEqualizerText {
            get {
                return ResourceManager.GetString("OpenEqualizerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to osu! location: {0}.
        /// </summary>
        public static string OsuLocationText {
            get {
                return ResourceManager.GetString("OsuLocationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to osu!profile ID (NOT URL).
        /// </summary>
        public static string OsuProfileIDNU {
            get {
                return ResourceManager.GetString("OsuProfileIDNU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to osu!profile ID.
        /// </summary>
        public static string OsuProfileIDPlaceholder {
            get {
                return ResourceManager.GetString("OsuProfileIDPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patch-notes.
        /// </summary>
        public static string PatchNotesTitle {
            get {
                return ResourceManager.GetString("PatchNotesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to playlist editor.
        /// </summary>
        public static string PlaylistEditorText {
            get {
                return ResourceManager.GetString("PlaylistEditorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist Editor.
        /// </summary>
        public static string PlaylistEditorTitle {
            get {
                return ResourceManager.GetString("PlaylistEditorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to playlist songs.
        /// </summary>
        public static string PlaylistSongsTitle {
            get {
                return ResourceManager.GetString("PlaylistSongsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} songs played.
        /// </summary>
        public static string SongsPlayed {
            get {
                return ResourceManager.GetString("SongsPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorting mode.
        /// </summary>
        public static string SortingModeTitle {
            get {
                return ResourceManager.GetString("SortingModeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start import.
        /// </summary>
        public static string StartImportText {
            get {
                return ResourceManager.GetString("StartImportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup song.
        /// </summary>
        public static string StartupSongTitle {
            get {
                return ResourceManager.GetString("StartupSongTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sure?.
        /// </summary>
        public static string SureQuestion {
            get {
                return ResourceManager.GetString("SureQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalXP.
        /// </summary>
        public static string TotalXP {
            get {
                return ResourceManager.GetString("TotalXP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to type to search for settings.
        /// </summary>
        public static string TypeToSearchPlaceholder {
            get {
                return ResourceManager.GetString("TypeToSearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Settings.
        /// </summary>
        public static string UserSettingsTitle {
            get {
                return ResourceManager.GetString("UserSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window Blur Method.
        /// </summary>
        public static string WindowBlurMethodTitle {
            get {
                return ResourceManager.GetString("WindowBlurMethodTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Description.
        /// </summary>
        public static string YourDescription {
            get {
                return ResourceManager.GetString("YourDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your playlists.
        /// </summary>
        public static string YourPlaylistsTitle {
            get {
                return ResourceManager.GetString("YourPlaylistsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your session.
        /// </summary>
        public static string YourSessionTitle {
            get {
                return ResourceManager.GetString("YourSessionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your songs.
        /// </summary>
        public static string YourSongsTitle {
            get {
                return ResourceManager.GetString("YourSongsTitle", resourceCulture);
            }
        }
    }
}
